#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "post-commit"

# Get the type and message of the last commit in the main repository
LAST_COMMIT=$(git log -1 --pretty=%B)
TYPE=$(echo $LAST_COMMIT | cut -d'(' -f1)
MESSAGE=$(echo $LAST_COMMIT | cut -d')' -f2 | xargs)

# Loop through all submodules
for SUBMODULE in $(git submodule --quiet foreach 'echo $path'); do
  SUBMODULE_PATH=$(echo $SUBMODULE | sed 's#^libs/##;s#^apps/##');
  if ! git diff --quiet HEAD; then
    cd "$SUBMODULE" && git add . && git commit -m "$TYPE($SUBMODULE_PATH)$MESSAGE" || : && git push;
    echo "$SUBMODULE";
    echo pwd;
    git add $SUBMODULE && git commit --no-verify -m "chore(test-app): updated git ref [skip ci]";
    echo "DONE: $SUBMODULE";
  fi
done

exit 0
