#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "pre-push"

git add .
git commit --no-verify -m "chore(test-app): updated git ref [skip ci]"
git push --no-verify
git pull origin --ff --no-verify
