#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "pre-push"

git add $(git submodule foreach --recursive 'echo $(pwd)')
git commit --no-verify -m "chore(test-app): updated git ref [skip ci]"
