#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "pre-push"

SUBMODULE_DIRS=$(git submodule foreach --quiet 'echo $path')
git add $SUBMODULE_DIRS
git commit --no-verify -m "chore(test-app): updated git ref [skip ci]"
